@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package enginecrafter77.survivalinc.stats;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
