@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package enginecrafter77.survivalinc.stats.impl;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
