# This workflow will build the mod using Gradle and then publish it to Curseforge when a release is published
name: Github Binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout tree
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Gradle Build
      run: ./gradlew build

    - name: Upload Binaries
      run: ./.github/scripts/upload-artifact.sh
      shell: bash
      environment: github-binaries
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
